[project]
name = "canny"
version = "0.1.0"
description = ""
readme = "readme.md"
requires-python = ">=3.13"
dependencies = [
    "torch>=2.8.0",
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "matplotlib>=3.10.5",
    "more-itertools>=10.7.0",
    "mypy>=1.17.1",
    "pytest>=8.4.1",
    "ruff>=0.12.8",
    "torchvision>=0.23.0",
    "uv-build>=0.8.6",
    "PyQt6",
]
