---
name: "Publish"

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  run:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install Python
        run: uv python install 3.13.9
      - name: Build
        run: uv build --package canny_chenn

      - name: Smoke test (wheel)
        run: uv run --isolated --no-project --with dist/*.whl packages/canny_chenn/test/test_smoke.py
      - name: Smoke test (source distribution)
        run: uv run --isolated --no-project --with dist/*.tar.gz packages/canny_chenn/test/test_smoke.py
      - name: Publish
        run: uv publish
